language: ruby
env:
  global:
  - TRAVIS_NODE_VERSION="6.9.5"
  - secure: LEzxenJrLI0mBVoijQPlNZJEBi/bfPFizwnI7kX1M/AMeTFwysTCNQXapTkKFST3n+WJ3ag1yWosDR4JrG/ZN9Yj770oIma70lrIA4sKKV5pRN+B8vFOIvHz5Lf0FEkBgcTiw+uHWTiPWz46AUr3ldKa6dhLK00p+DvhZUDTEDeAfnFn5FarRAOqj8A6CSXNN92o86WEHWC1s0CeoJtSy74woiC280285ddWyPKsgBm5i2vyYOiNQ00JohqZp10DY3Ptq+ejR32IXBOOYj+j/KWdRs19djNPWMY/OcZJ9R0FIo2xiZDrJkmDyiKiwfMru8E40jvITIWLCVW9ByR7p2jSP3SA4wYI/0tkS/VQ/qrr+op7L22YCambOvjMXZsPRBD2rY2K3nhkUjQVgkXOoVay1jr3px34ITuU9ALjeCBat9TrJEPJHq8142ajpzlheTqH6rFm0btb0iXBizHwQuy3ghViqXSn3SlIR+wptb5VC1KH5f7EGq0LkXxTAm7OMZLPzGwBsxkX8UccC/a9/RdfOC19e2pJ5M487JjZez2FBvueyd3BJGUePiI6p/4uh3kUTzEJxS/Tok0rtOGbium8+bL91pr3bcfbQVFN+RLws8D6aG0c576TmaNRnIxXnVwkBH8he8Eyip08jhAmr4GKGLxnSgYhNFZEdhX3EDw=
install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm
- "(cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)"
- source ~/.nvm/nvm.sh
- nvm install $TRAVIS_NODE_VERSION
- gem install bundler jekyll
- bundle install --path vendor/bundle
- npm install
script:
- jekyll build
after_success:
- npm install aerobatic-cli -g
- aero deploy     --commit-url "https://github.com/vosaul/k1.git"     --directory _site
