language: ruby
env:
  global:
  - TRAVIS_NODE_VERSION="6.9.5"
  - secure: "YWiYYVWnQOGTDdS1gLWB2U8aH34/W71FYaisLW25LN6+l6pertWKbDuFlMkbpWptIp0w8hgFu1yOHGDHjHkvzog3yEgwqMCeuiGzFsS06tuzTREMgGe0QmHGgHiHHUdDbGlcBXY60K6JMFHsiNeTx83TSsLzR9B3/Ez4brjvF3BiOYub5wFp/0DNJQOwpEZc+YBIAkiVm2HwfiDHbHMTLQeRds1jLGWFFKDirWHGcjeiuzqoH+XB25Sez6ozyf6tB5vnPR3nudbPRqBWdQaI+z14SHBHkeIWxnuvqSP0+USyJvWWrJ+PGiV8PYxKXXZ159AlP+VBRczh46EWiMpmnuGFOkmrZ8UwtJRPcQUWJVqx7UkzuGN4I20/ZsJPHe0M6j1PG/G5T3XEAxHSY3AlyWh068avh3NwAAjcHatmJBPHvzrq2HeQpQIowjbRDLsm3vdjNxsJ/me5eHvHz6gC7IE9e2+Suv2cI0Jm5/NgaX0LsDjoitk9EV7oyJn6vgAwDEVjwRjEpXVIGr1n1QI3JgUtn+JF//p+EvvwLySOHkxvexv5ymXF4HAg3JbxWPSk/LV/qzX2tZjHpZYFVufyV5pHFMvM1UjYF3l9azFoAMOINNWNCgnkUEvd773BwJ1RUQM4ULCuQ/J3VKKbAT7P5jpG9P6Bu/p5zhgesqxRVw4="
install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm
- "(cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)"
- source ~/.nvm/nvm.sh
- nvm install $TRAVIS_NODE_VERSION
- gem install bundler jekyll
- bundle install --path vendor/bundle
- npm install
script:
- jekyll build
- after_success:
  - npm install aerobatic-cli -g
  - aero deploy     --commit-url "https://github.com/owner/repo-name/commit/${TRAVIS_COMMIT}"    --directory _site
